server:
    port: 8080

spring:
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5432/keeperdb
    username: postgres
    password: myRea11ySecRett0Pass
    platform: postgres
    continue-on-error: true
    dbcp2:
      driver-class-name: org.postgresql.Driver

  resources:
    static-locations: classpath:/resources/static/**, classpath:/META-INF/resources/, classpath:/META-INF/resources/webjars/

  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

  thymeleaf:
    cache: true
    mode: LEGACYHTML5

logging:
  level: error

---

spring:
  profiles: local
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/keeperdb
    username: postgres
    password: postgres
    platform: postgres
    continue-on-error: true
    dbcp2:
      driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false
    mode: LEGACYHTML5

---

spring:
  profiles: dev

logging:
  level: debug
