server:
    port: 8080

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    dbcp2:
      driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://137.74.114.219:19009/keeperdb
    username: postgres
    password: myRea11ySecRett0Pass
    platform: postgres
    continue-on-error: true
  resources:
    static-locations: classpath:/resources/static/, classpath:/META-INF/resources/, classpath:/META-INF/resources/webjars/

  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
#logging:
#  level: error

#---

#spring:
#    profiles: dev

logging:
  level: warn
